#  **Практическое занятие №2. Линейная алгебра.**

## Знакомство с библиотекой **NumPy**

numpy - библиотека для быстрой работы с большими массивами и матрицами

https://numpy.org/doc/stable/user/quickstart.html

In [55]:
import numpy as np

### Мотивация: numpy vs python

In [2]:
import time

arr_size = 1000000
iter_num = 1000

In [3]:
# time pure python list sum
x = list(range(arr_size))

s = time.time()

for i in range(iter_num):
    sum(x)

t = time.time() - s

print(f'Finished in {t:.5f} s: {(t * 1000 / iter_num):.5f} ms per iteration')

Finished in 8.00034 s: 8.00034 ms per iteration


In [4]:
# time numpy array sum
x = np.arange(arr_size)

s = time.time()

for i in range(iter_num):
    np.sum(x)

t = time.time() - s

print(f'Finished in {t:.5f} s: {(t * 1000 / iter_num):.5f} ms per iteration')

Finished in 0.50988 s: 0.50988 ms per iteration


### Basics

#### Создание массива
https://numpy.org/doc/stable/reference/routines.array-creation.*html*

In [5]:
# создать явно
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# нулевой массив заданного размера
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# нулевой массив такого же размера, как другой
a = np.array([[1, 2, 3], [4, 5, 6]])
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
# массив единиц заданного размера
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# массив единиц такого же размера, как другой
a = np.array([[1, 2, 3], [4, 5, 6]])
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
# массив, заполненный конкретным числом
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
# массив, заполненный конкретным числом
a = np.array([[1, 2, 3], [4, 5, 6]])
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [14]:
# создать единичную матрицу (двумерный массив)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# создать range
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [23]:
# можно явно указать тип при создании массива вторым аргументов
np.zeros((2, 3), np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [20]:
# заполнить из функции
np.fromfunction(lambda i, j: i * j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [21]:
# можно заменить тип
a = np.array([1, 2, 5])
a.astype('str')

array(['1', '2', '5'], dtype='<U21')

In [22]:
# посмотреть все возможные типы
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

#### Доступ к элементам массива, срезы
https://numpy.org/doc/stable/user/basics.indexing.html



##### Доступ к элементам

In [25]:
# доступ по индексу, включая негативные индексы
a = np.arange(10)
a[-2]

8

In [27]:
# доступ по набору индексов, включая негативные
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
a[1,4]

9

In [28]:
# можно выделять индекс по каждому срезу отдельными скобками - но это менее эффективно
a[1][3] # same as a[1,3]

8

In [29]:
# можно изменять значение по индексу
a = np.arange(5)
a[0] = 5
a

array([5, 1, 2, 3, 4])

##### Срезы, слайсы

In [45]:
a = list(range(10))
a[8:1:-2]

[8, 6, 4, 2]

In [31]:
# работает привычный питонячий слайсинг
a = np.arange(10)
a[8:1:-2]

array([8, 6, 4, 2])

In [33]:
# срез по первой оси
a = np.array([[[0, 1, 2],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
a.shape

(2, 2, 3)

In [36]:
a[0] # same as a[0,:,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
# срез по произвольной оси
a = np.array([[[0, 1, 2],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
a[:,:,0] # same as a[:,0,:]

array([[0, 3],
       [6, 9]])

In [39]:
# срез + слайс
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
a[0,-1:0:-2]

array([3, 1])

In [46]:
a.copy()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
# можно задавать срезы/слайсы программно
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])

i = np.array([0, 2])
s = slice(-1, 0, -2)

a[i,s]

array([[ 3,  1],
       [11,  9]])

In [41]:
a[np.array([0, 2]),-1:0:-2]

array([[ 3,  1],
       [11,  9]])

In [47]:
# !!! срезы/слайсы не копируют массивы, а возвращают "представление"
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])

b = a[0]
b[2] = 100

a

array([[  0,   1, 100,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

Задача. Создать матрицу с единицами на побочной диагонали и нулями вне ее.

In [44]:
# your code here
np.eye(5)[:,::-1]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

##### Форма массива и ее изменение

In [48]:
a = np.arange(12)
a.shape

(12,)

In [49]:
b = a.reshape(2, 6)
b.shape

(2, 6)

In [50]:
# важно сохранять размеры при изменении формы
c = a.reshape(2, 4)

ValueError: ignored

In [51]:
# можно использовать -1, тогда размер вдоль этой оси будет автоматически вычисляться
c = a.reshape(2, -1)
c.shape

(2, 6)

In [52]:
# развернуть массив в одномерный
d = c.ravel()
d.shape

(12,)

In [53]:
# !!! изменение формы тоже возвращает "представление"
a = np.arange(10)

b = a.reshape(2, 5)
b[0][3] = 100

a

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

#### Операции с массивами

##### Арифметические операции

Операции с числами выполняются **поэлементно**



In [54]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [56]:
a + 1

array([[2, 3],
       [4, 5]])

In [57]:
a - 1

array([[0, 1],
       [2, 3]])

In [58]:
a * 2

array([[2, 4],
       [6, 8]])

In [59]:
a / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [60]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

Математические операции между матрицами тоже выполняются **поэлементно**

In [61]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [1, 2]])

In [62]:
a + b

array([[4, 6],
       [4, 6]])

In [63]:
a - b

array([[-2, -2],
       [ 2,  2]])

In [64]:
a * b

array([[3, 8],
       [3, 8]])

In [65]:
a / b

array([[0.33333333, 0.5       ],
       [3.        , 2.        ]])

Формы массивов могут не совпадать, главное - чтобы они были **broadcastable**

https://numpy.org/doc/stable/user/basics.broadcasting.html

In [66]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([0, 1, 2])
c = np.array([[0, 1, 2], [0, 1, 2]])

print(a.shape, b.shape, c.shape)

(2, 3) (3,) (2, 3)


In [68]:
a + b

array([[1, 3, 5],
       [4, 6, 8]])

In [69]:
a + c

array([[1, 3, 5],
       [4, 6, 8]])

Задача. Создать квадратную матрицу размера N с квадратами чисел от N до 1 на главной диагонали

In [72]:
# your code here
a = np.eye(10)
b = np.arange(10, 0, -1)
c = (a * b) ** 2

c

array([[100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  81.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  49.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  36.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  25.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  16.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   4.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.]])

##### Математические функции

https://numpy.org/doc/stable/reference/routines.math.html

In [73]:
# поэлементные функции
a = np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
# агрегатные функции
a = np.array([[1, 2], [3, 4]])
np.sum(a)

10

In [76]:
# можно задавать ось
a = np.array([[1, 2], [3, 4]])
np.sum(a, 0)

array([4, 6])

##### Матричные операции

Транспонирование матрицы

In [77]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [78]:
a.T

array([[1, 3],
       [2, 4]])

In [79]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [80]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

Операция matmul - умножение матрицы на вектор, и матрицы на матрицу

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

In [81]:
# два вектора - скалярное произведение
a = np.array([2., 3., 4.])
b = np.array([-2., 1., -1.])

a @ b

-5.0

In [82]:
# матрица и вектор - умножение матрицы на вектор
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([-1, 3, 2])

a @ b

array([11, 23, 35])

In [83]:
# две матрицы
a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
b = np.array([[1, 2], [3, 4], [5, 6]])

a @ b

array([[22, 28],
       [40, 52],
       [58, 76]])

In [84]:
# важно, чтобы матрицы соответствовали по размеру (число столбцов первой матрицы равнялось число строк второй)
b @ a

ValueError: ignored

In [87]:
# если размерность одного массива больше 2?
a = np.ones((12, 5, 3, 4))
b = np.ones((4, 5))

c = a @ b
c.shape

(12, 5, 3, 5)

In [92]:
# а если обоих?
a = np.ones((2, 3, 4))
b = np.ones((7, 4, 5))

c = a @ b
c.shape

ValueError: ignored

Операция dot - тоже умножение, но есть нюанс

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [89]:
# если размерность одного массива больше 2?
a = np.ones((2, 3, 4))
b = np.ones((4, 5))

c = a.dot(b)
c.shape

(2, 3, 5)

In [91]:
# а если обоих?
a = np.ones((2, 3, 4))
b = np.ones((7, 4, 5))

c = a.dot(b)
c.shape

(2, 3, 7, 5)

Обратная матрица и определитель

In [93]:
# определитель
a = np.eye(10)

print(a)
print(np.linalg.det(a))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
1.0


In [94]:
b = 5 * np.eye(6) + np.ones(6)

print(b)
print(np.linalg.det(b))

[[6. 1. 1. 1. 1. 1.]
 [1. 6. 1. 1. 1. 1.]
 [1. 1. 6. 1. 1. 1.]
 [1. 1. 1. 6. 1. 1.]
 [1. 1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1. 6.]]
34374.99999999999


In [95]:
# обратная матрица
a = np.array([[1, 2], [3, 4]])
b = np.linalg.inv(a)

b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [96]:
a @ b

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [97]:
np.allclose(a @ b, np.eye(2))

True

In [99]:
# обратная матрица не всегда существует
a = np.array([[1, 0], [2, 0]])
np.linalg.det(a)

0.0

Задача. Решить систему линейных уравнений
$$
a_{11} x_1 + ... + a_{1n} x_n = b_1
$$
$$
...
$$
$$
a_{n1} x_1 + ... + a_{nn} x_n = b_n
$$

В матричном виде $Ax = b$

In [100]:
def solve_eq(A, b):
    # your code here
    return np.linalg.inv(A) @ b

In [103]:
A = np.random.random((5, 5))
b = np.arange(5)

x = solve_eq(A, b)

assert np.allclose(A @ x, b)